### ISSUE TITLE
Kartenlegende für die Farben der Punkte.

### ISSUE THREAD

**Issue by FrankZter** [mrkwnzl/orca-nrw-karte#1]
Da man die Farben der Punkte erst erklärt bekommt, wenn man auf das Symbol oben rechts klickt wäre es schön, wenn wir eine extra Legende basteln, die die Farben erklärt. Diese Legende kann am besten so aussehen wie die in dem Layermenü. Diese Legende sollte dann immer sichtbar sein (unten rechts?)

**Comment by mrkwnzl** [comment]
Erledigt in v0.1
