### ISSUE TITLE
Bezeichnung der Phase 0

### ISSUE THREAD

**Issue by FrankZter** [mrkwnzl/orca-nrw-karte#12]
Phase 0 bedeutet, dass die HS noch keine Policy hat. Alle Hochschulen die wir auflisten sind aber Teil des ORCA Netzwerks.

https://github.com/mrkwnzl/orca-nrw-karte/blob/a0aaee87b281072c8f132a6aa07197f9cf2afaa0/README.md?plain=1#L44

**Comment by mrkwnzl** [comment]
Korrigiert zu „Noch keine Policy“, weil es so auch auf der Karte auftaucht. Da nur ORCA-Mitglieder gelistet sind, sollte der Punkt klar sein.
