### ISSUE TITLE
Karte im Breitformat

### ISSUE THREAD

**Issue by FrankZter** [mrkwnzl/orca-nrw-karte#3]
In Anlehnung an die alte Netzwerkkarte und an das breite Format der Homepage fände ich es chic wenn die Karte auch in einem Breitformat wäre oder zumindest etwas größer da die Objekte auf der Website insgesamt alles groß sind.

**Comment by mrkwnzl** [comment]
Das Problem ist, das die Karte nicht im Breitformat ist. Da können wir auch nicht viel dran machen. NRW ist halt eher quadratisch als rechteckig.

**Comment by FrankZter** [comment]
Ich kann die Karte also die Grafikdatei so erweitern, dass es ein breiteres Format wird. 
Die derzeitige Karte füllt hat die Seite besser aus finde ich. (Auch wenn es das einzige ist, was diese Karte besser kann)
![image](https://user-images.githubusercontent.com/70097264/187597217-21b212ba-d5e8-4f88-ab10-2c41a1b28b53.png)

**Comment by mrkwnzl** [comment]
Das ist doch Quatsch. Das ist ne Karte, die auf allen möglichen Seiten eingebunden werden können soll. Dann stylen wir die doch nicht spezifisch für eine Seite und vor allem erstellen wir doch keine Karte, die zu 50% aus unnützer Info besteht oder die zu 50% leer ist.

**Comment by mrkwnzl** [comment]
Okay, hab ne Lösung. Man kann die Größe des iframes einstellen. Das initiale Zoom-Level hängt nun davon ab, ob die Höhe oder Breite des iframes größer als die Karte (524 × 524 px) ist. Wenn ja, startet die Karte gezoomt. Wenn nein, ist sie komplett sichtbar.

iframe 524 × 1024 px:
<img width="1055" alt="Screen Shot 2022-08-31 at 08 24 46" src="https://user-images.githubusercontent.com/40534855/187608361-ed659d35-e7f2-422d-945c-43f9da50aaec.png">

iframe 524 × 524 px:
<img width="751" alt="Screen Shot 2022-08-31 at 08 25 35" src="https://user-images.githubusercontent.com/40534855/187608478-6263424e-5203-4310-b3d7-307b3761dc4d.png">

**Comment by FrankZter** [comment]
Dafür, dass du so losgepöbelt hast, hast du aber einer sehr gute Lösung gefunden! ❤

**Comment by FrankZter** [comment]
Ich hab das mal wieder aufgemacht, bis wir die Karte verbreitert haben :)

**Comment by mrkwnzl** [comment]
Die Karte verbreitert sich dynamisch. Das kann jetzt schon gemacht werden. im iframe muss einfach nur eine andere Breite angegeben werden.
