### ISSUE TITLE
andere Policy

### ISSUE THREAD

**Issue by sOER-Frank** [mrkwnzl/orca-nrw-karte#6]
Manche Hochschulen haben keine explizite OER Policy sondern haben z.B. in einer Open Science Policy oder einer open Access Policy ein Kapitel oder einen Abschnitt zu OER gemacht. Wie gehen wir damit um? 
Man könnte entweder die Überschrift ändern:
![image](https://user-images.githubusercontent.com/70097264/187389190-77d43276-67ef-4e33-a405-96070235251e.png)
Oder wir lassen die Überschrift und schreiben darunter dann sowas wie "Veröffentlicht in Open Science Policy" oder "keine eigenständige OER Policy".

**Comment by mrkwnzl** [comment]
Ich hab das im develop-Branch als „Open Content Policy“ bezeichnet, weil ich das für recht allgemeingültig hielt. Würde das passen?

**Comment by mrkwnzl** [comment]
Wurde von ORCA.nrw auf „OER Policy“ festgelegt.
