### ISSUE TITLE
Uni Duisburg Essen in Standorte aufteilen

### ISSUE THREAD

**Issue by FrankZter** [mrkwnzl/orca-nrw-karte#7]
Die Uni Duisburg-Essen ist mit zwei Standorten vertreten. Ich glaube es wird sehr voll wenn wir beide Netzwerkstellen auf einen Popup quetschen. Daher würde ich empfehlen, dass wir die UDE einmal als "UDE - Standort Duisburg" und einmal als "UDE - Standort Essen". **Wir brauchen also für die UDE einen zweiten Punkt auf der Karte.**

**Comment by mrkwnzl** [comment]
Ne, die teilen doch alle Ressourcen. Gleiche Website, gleiche Förderung. Ist doch egal, in welchem Gebäude die dann arbeiten. Genaue Infos findet man dann im Profil.
